$lang{DATE_ADD} = 'Дата занесення дерева в реєстр';
$lang{TREE_ADD} = 'Додати дерево';
$lang{NUMBER_REGISTRATION} = 'Реєстраційний номер дерева';
$lang{TREE_TYPE} = 'Порода дерева';
$lang{TREE_AGE} = 'Вік дерева ( в роках )';
$lang{TREE_HEIGHT} = 'Висота дерева, м';
$lang{TREE_CIRCUMFERENCE} = 'Окружність стовбура дерева, м';
$lang{TREE_STATUS} = 'Статус';
$lang{COMMENT} = 'Коментар';
$lang{PARK_TRYLOVSKIY} = 'Парк Трильвського';
$lang{TREE_NUMBER_REGISTRATION} = 'Дерево, реєстраційний номер';
$lang{TREE_EDIT} = 'Редагування дерева';
$lang{TREE_SEARCH} = 'Пошук дерева';
$lang{ADD}='Додати';
$lang{SUBMIT}='Додати';
$lang{X}='Геолокація: Координата X';
$lang{Y}='Геолокація: Координата Y';
$lang{FROM_AGE} = 'Вік від';
$lang{TO_AGE} = 'Вік до';
$lang{O2} = 'Кількість виробляючого кисню: кг/день: ';
$lang{CO2} = 'Кількість виробляючого вуглекислого газу: кг/день: ';
$lang{MID_AGE} = 'Середній вік дерев ( в роках ): ';

1;
