#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';
use Trees::db::Trees;
require Abills::Templates;
our ($db, $admin, %conf, %lang, $html);
our Trees $Trees = Trees->new($db, $admin, \%conf);

#**********************************************************

=head2 trees_add()

=cut

#**********************************************************
sub trees_add {

  #Abills::Base::_bp("name",\%FORM,{HEADER => 1});

    # Add template
    $html->tpl_show(
      _include('trees_add', 'Trees'),
      {
        SUBMIT => $html->form_input('add', $lang{ADD}, { TYPE => 'submit' }),

      }
    );

  }

  #Adding a new tree to bd
  if ($FORM{add}) {
    $Trees->add(
      {
        TREE_AGE    => $FORM{AGE},
        TREE_HEIGHT => $FORM{HEIGHT},
        TREE_CIRCLE => $FORM{CIRCLE},
        TREE_TYPE   => $FORM{ADD_TREE_SORT},
        TREE_STATUS => $FORM{STATUS},
        COMMENT     => $FORM{COMMENT},
        X           => $FORM{X},
        Y           => $FORM{Y},
      }
    );
    if (!$Trees->{errno}) {
      $html->message('info', $lang{SUCCESS});
    }
    else {
      $html->message('err', $lang{ERROR}, $Trees->{errno} . " : " . $Trees->{errstr});
    }
  

}


  #**********************************************************

=head2 search_form()

=cut

#**********************************************************
  sub search_form {
  # Add search template 
  $html->tpl_show(
    _include('trees_search', 'Trees'),
    {
      SEARCH => $html->form_input('search', $lang{TREE_SEARCH}, { TYPE => 'submit' }),

    }
  );

  if ($FORM{search}) {
    my $lest = $Trees->search(
      {
        TREE_AGE    => $FORM{AGE},
        TREE_AGE2    => $FORM{AGE2},
        TREE_TYPE   => $FORM{ADD_TREE_SORT},
        TREE_STATUS => $FORM{STATUS},

      }
    );
    if (!$Trees->{errno}) {
      $html->message('info', $lang{SUCCESS});

    }
    else {
      $html->message('err', $lang{ERROR}, $Trees->{errno} . " : " . $Trees->{errstr});
    }
#Delete a tree
if ($FORM{del}) {

    $Trees->del($FORM{del});
    if (!$Trees->{errno}) {
      $html->message('info', $lang{SUCCESS});
    }
    else {
      $html->message('err', $lang{ERROR}, $Trees->{errno} . " : " . $Trees->{errstr});
    }
  }





    # output header of table from search form

    my $table = $html->table(
      {
        width   => '100%',
        caption => 'Trees',
        border  => 2,
        title   => [ 'id', $lang{TREE_AGE}, $lang{TREE_HEIGHT}, $lang{TREE_CIRCUMFERENCE}, $lang{TREE_TYPE}, $lang{TREE_STATUS}, $lang{X}, $lang{Y}, '-', '-' ],
        cols_align => [ 'center', 'center', 'center', 'center', 'center', 'center', 'center' ],
        pages      => $Trees->{TOTAL},
        ID         => 'COMPANY_ID'
      }
    );

    my $list = $Trees->search(
      {
        TREE_AGE    => $FORM{AGE},
        TREE_HEIGHT => $FORM{HEIGHT},
        TREE_CIRCLE => $FORM{CIRCLE},
        TREE_TYPE   => $FORM{ADD_TREE_SORT},
        TREE_STATUS => $FORM{STATUS},
        X           => $FORM{X},
        Y           => $FORM{Y},
        ,
        COLS_NAME => 1
      }
    );


 
    # output data of table from search form
    foreach my $line (@$list) {
      $table->addrow(
        $line->{id},
        $line->{tree_age},
        $line->{tree_height},
        $line->{tree_circle},
        $line->{tree_type},
        $line->{tree_status},
        $line->{x},
        $line->{y},
        $html->button('change', 'change', { TYPE => 'submit' }),
        $html->button('del', 'del', { class => 'btn' }),

      );

    }


    print $table->show();



}
}

#**********************************************************

=head2 search_count()

=cut

#**********************************************************

sub search_count {
    my $Trees = Trees->new($db, $admin, \%conf);
    

my $result = $Trees->search_count();
my $count = $result->[0]->{number_trees};
my $count_age = $result->[0]->{sage_trees};


 if ( $result ){

my $rez_o2 = ($count*2.5);
my $rez_co2 = ($count*1.7);
my $rez_mid_age = ($count_age/$count);
 $html->tpl_show(
    _include('additional_parametres', 'Trees'),{O2 => $rez_o2,
CO2 => $rez_co2,
AGE => $rez_mid_age 
},

);




}


}






1;

