$lang{DATE_ADD}                 = 'Дата внесения дерева в реестр';
$lang{TREE_ADD}                 = 'Добавить дерево';
$lang{NUMBER_REGISTRATION}      = 'Регистрационный номер дерева:';
$lang{ADDITIONAL_ALGORITHMS}    = 'Дополнительные параметры';
$lang{TREE}                     = 'Реестр деревьев';
$lang{TREE_TYPE}                = 'Порода дерева:';
$lang{TREE_AGE}                 = 'Вoзраст дерева:';
$lang{TREE_HEIGHT}              = 'Высота дерева:';
$lang{TREE_CIRCLE}              = 'Окружность ствола дерева:';
$lang{TREE_STATUS}              = 'Статус:';
$lang{COMMENT}                  = 'Комментарий';
$lang{PARK_TRYLOVSKIY}          = 'Парк Трильовского';
$lang{TREE_NUMBER_REGISTRATION} = 'Дерево, регистрационный номер';
$lang{TREE_EDIT}                = 'Редактирование дерево';
$lang{TREE_SEARCH}              = 'Поиск дерева';
$lang{ADD}                      = 'Добавить';
$lang{SUBMIT}                   = 'Добавить';
$lang{X}                        = 'Геолокация: Координата X';
$lang{Y}                        = 'Геолокация: Координата Y';
$lang{to}                       = 'до';
$lang{FROM_AGE} = 'Возраст от ( в годах ) ';
$lang{TO_AGE} = 'Возраст до ( в годах )';
$lang{O2} = 'Количество вырабатываемого кислорода: кг/день: ';
$lang{CO2} = 'Количество вырабатываемого углекислого газа: кг/день: ';
$lang{MID_AGE} = 'Средней возраст всех деревьев ( в годах ): ';

1;
