#!perl
=head1 NAME
 Trees
=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Trees::db::Trees;
use Data::Dumper;

#our ($db, $admin, %conf, %lang, $html);
#my $Trees = Trees->new($db, $admin, \%conf);

our ($html, %FORM, $db, %conf, $admin, %lang, $index);
my  ($table, $button_add, $button_change);

#**********************************************************
=head2 add_trees() 
  add_trees
  Returns:
  1
=cut
#**********************************************************
sub add_trees {
    my $Trees = Trees->new($db, $admin, \%conf);
    #my $type_list = $Tree->type_list({ COLS_NAME => 1 });
    #my $species = $Tree->species_list({ COLS_NAME => 1 });
    #my @files_type = ();
    #my @files_species = ();
    my $place = 'Home';
    my $value_x = 48.537917;
    my $value_y = 25.024278;
    my $location_id = 1;

    if ($FORM{ADD}) {
        $Trees->add_trees({
            TREE_AGE     => $FORM{AGE},
            TREE_HEIGHT  => $FORM{HEIGHT},
            TREE_CIRCLE  => $FORM{CIRCLE},
            TREE_TYPE    => $FORM{SORT},
            TREE_STATUS  => $FORM{STATUS},
            VALUE_X     => $FORM{VALUE_X},
            VALUE_Y     => $FORM{VALUE_Y},
            COMMENT    => $FORM{COMMENT},
        });
        $html->message('info', $lang{SUCCESS});
    }
    elsif ($FORM{del}) {
        $Trees->del_species({ ID => $FORM{del} });
        $html->message('err',$lang{ERROR}, $Trees->{errno} . " : " . $Trees->{errstr});
    }
    elsif ($FORM{CHANGE}) {
        $Trees->species_change(\%FORM);
        $html->message('warn', $lang{ERROR}, $Trees->{errno} . " : " . $Trees->{errstr});
    }

    $button_add = $html->form_input("ADD", $lang{ADD}, { TYPE => "submit" });
    #$button_change = $html->form_input("CHANGE", $lang{CHANGE}, { TYPE => "submit" });

    $html->tpl_show(_include('trees_add', 'Trees'), {
        ID            => $FORM{ID},
        INDEX         => $index,
        BUTTON_ADD    => $button_add,
       # BUTTON_CHANGE => $button_change,
        SORT           => $html->form_input('SORT', $FORM{sort}),
        AGE           => $html->form_input('AGE', $FORM{age}),
        HEIGHT        => $html->form_input('HEIGHT', $FORM{height}),
        CIRCLE        => $html->form_input('CIRCLE', $FORM{circle}),
        STATUS       => $html->form_input('STATUS', $FORM{status}),
        COMMENT       => $html->form_input('COMMENT', $FORM{comment}),
        VALUE_X        => $html->form_input('VALUE_X', $FORM{value_x}),
        VALUE_Y        => $html->form_input('VALUE_Y', $FORM{value_y}),
        PLACE         => $place,
        VALUE_X       => $value_x,
        VALUE_Y       => $value_y,
        LOCATION_ID   => $location_id
    });
    return 1;
}
#**********************************************************
=head2 search_trees() 
  search_trees
  Returns:
  1
=cut
#**********************************************************

sub search_tree {
  my ($button_search, $button_clear);

    if ($FORM{EDIT}) {
        $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_SORT});
    }

  my $style            = "box box-theme collapsed-box";
  
  my $Tree          = Tree->new($db, $admin, \%conf);
  if($FORM{DRAW}) {
        # Abills::Base::_bp("", \%FORM);
        $Tree->tree_change({
            ID         => $FORM{ID},
            EXT_ID     => $FORM{EXT_ID},
            SPECIES_ID => $FORM{SORT},
            AGE        => $FORM{AGE},
            STATUS     => $FORM{STATUS_EDIT},
            COMMENT    => $FORM{COMMENTS},
        });
        $style = "box box-theme collapsed-box";
    } elsif ($FORM{EDIT}) {
        $style = "box box-theme";
    }
  my $tree_list;
  if(!$FORM{DRAW}){
  $tree_list     = $Tree->tree_list({
      COLS_NAME  => 1,
      MIN_AGE    => $FORM{MIN_AGE},
      MAX_AGE    => $FORM{MAX_AGE},
      TYPE_ID    => $FORM{TYPE},
      SPECIES_ID => $FORM{SORT},
      STATUS     => $FORM{STATUS},
  });}
  else{
      $tree_list     = $Tree->tree_list({
      COLS_NAME  => 1,
      });
  };

    my $type_list     = $Tree->type_list({COLS_NAME    => 1});
    my $sort_list     = $Tree->species_list({COLS_NAME => 1});
    my @status_tree   = ('Здорове', 'Хворе');
    my $button_edit   = $html->form_input('DRAW', $lang{EDIT}, {TYPE => 'submit'});
    my @status_tree   = ('Здорове', 'Хворе');
    my @type = ();
    my @sort = ();


    # box box-theme collapsed-box
    # box box-theme

    

    $button_search = $html->form_input("SEARCH", $lang{SEARCH}, {TYPE => "submit"} );
    $button_clear  = $html->form_input("CLEAR",  $lang{CLEAR},  {TYPE => "submit"} );

    # $Tree->add_tree({
    #     EXT_ID     => "2",
    #     SPECIES_ID => 43,
    #     AGE        => 92,
    #     COORDX     => 48.5303,
    #     COORDY     => 25.5303,
    #     STATUS     => "Хворе",
    #     COMMENT    => " ",
    # });

    if ($FORM{del}) {
        $Tree->del_tree({ID => $FORM{del}})
    }

    # my $js_locations_arr;
    # foreach my $tree (@$tree_list){
    #     $js_locations_arr.= "[\"" . $tree -> {species} . "\"," . $tree -> {coordx} . "," . $tree -> {coordy} . "," . $tree -> {id} . "],";
    # }
    my $js_locations_arr;
    foreach my $tree (@$tree_list){
        my $name = "<h3>"           . $tree -> {species} . "</h3>" .
            "<b>Номер дерева: </b>" . $tree -> {ext_id}  . "<br>" .
            "<b>Вік: </b>"          . $tree -> {age}     . "<br>" .
            "<b>Статус: </b>"       . $tree -> {status};
        $js_locations_arr.= "[\"" . $name . "\"," . $tree -> {coordx} . "," . $tree -> {coordy} . "," . $tree -> {id} . "],";
    }


  push @type, "--";
  foreach my $line (@$type_list) {
    push @type, $line->{"type_of_tree"};
  }

  push @sort, "--";
  foreach my $line (@$sort_list) {
    push @sort, $line->{"species"};
  }

  $html->tpl_show(_include('main_page_three', 'Tree'), {
    ID            => $FORM{ID},
    INDEX         => $index,
    ONE_NUMB_YEAR => $html->form_input('MIN_AGE',  $FORM{MIN_AGE}),
    TWO_NUMB_YEAR => $html->form_input('MAX_AGE',  $FORM{MAX_AGE}),
    LOCATIONS_ARR => $js_locations_arr,
    STATUS        => $html->form_select(
      'STATUS',
      {
          SELECTED            => $FORM{STATUS},
          SEL_ARRAY           => \@status_tree,
          NO_ID               => 1,
          SEL_OPTIONS => { '' => '--' },
      }),
    TYPE          => $html->form_select(
      'TYPE',
      {
        SELECTED            => $FORM{TYPE},
        SEL_ARRAY           => \@type,
        ARRAY_NUM_ID        => 1,
          
      }),
    SORT             => $html->form_select(
      'SORT',
      {
        SELECTED            => $FORM{SORT},
        SEL_ARRAY           => \@sort,
        ARRAY_NUM_ID        => 1,
      }),
    DATE_CHANGE   => $html->form_input('DATE_CHANGE', $FORM{DATE_CHANGE}),
    BUTTON_SEARCH => $button_search,
    BUTTON_CLEAR  => $button_clear,
  });


    $html->tpl_show(_include('main_page_five', 'Tree'), {
        ID            => $FORM{ID},
        INDEX         => $index,
        TYPE          => $html->form_select(
            'TYPE',
            {
                SELECTED    => $FORM{TYPE},
                SEL_LIST    => translate_list($Tree->type_list({ COLS_NAME => 1 },
                    'type_of_tree')),
                SEL_KEY     => 'id',
                SEL_VALUE   => 'type_of_tree',
                NO_ID       => 1,
                SEL_OPTIONS => { '' => '--' },
            }),
        SORT          => $html->form_select(
            'SORT',
            {
                SELECTED    => $FORM{SPECIES_ID},
                SEL_LIST    => translate_list($Tree->species_list({ COLS_NAME => 1 },
                    'species')),
                SEL_KEY     => 'id',
                SEL_VALUE   => 'species',
                NO_ID       => 1,
                SEL_OPTIONS => { '' => '--' },
            }),
        ONE_NUMB_YEAR => $html->form_input('AGE', $FORM{AGE}),
        STATUS        => $html->form_select(
            'STATUS_EDIT',
            {
                SELECTED    => $FORM{STATUS_EDIT},
                SEL_ARRAY   => \@status_tree,
                SEL_OPTIONS => { '' => '--' },
                NO_ID       => 1,
            }),
        NUMBER_TREE   => $html->form_input('EXT_ID', $FORM{EXT_ID}),
        BUTTON_EDIT   => $button_edit,
        STYLE_BOX     => $style,
    });
  ($table, $tree_list) = result_former( {
		  #INPUT_DATA          => $Tree,
    LIST                => $tree_list,
    BASE_FIELDS         => 9,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, ext_id, species_id, species, age,
                            coordx, coordy, status, comment',
    EXT_TITLES          => {
      id                     => $lang{ID},
      ext_id                 => $lang{EXT_ID},
      species_id             => $lang{SPECIES},
        species              => $lang{TYPE},
      age                    => $lang{AGE},
      coordx                 => $lang{COORDX},
      coordy                 => $lang{COORDY},
      status                 => $lang{STATUS},
      comment                => $lang{COMMENT},
    },
    SKIP_PAGES          => 1,
    TABLE               => {
      width             =>  '100%',
      caption           =>  "$lang{LOGO}",
      qs                =>  $pages_qs,
      pages             =>  500,
      ID                =>  'TREES_ID',
    },
    MODULE              =>  'Tree',
  });

  foreach my $line (@$tree_list) {
        my @fields_array = ();

        push @fields_array, $line->{"id"};
        push @fields_array, $line->{"ext_id"};
        push @fields_array, $line->{"species"};
        push @fields_array, $line->{"type_of_tree"};
        push @fields_array, $line->{"age"};
        push @fields_array, $line->{"coordx"};
        push @fields_array, $line->{"coordy"};
        push @fields_array, $line->{"status"};
        push @fields_array, $line->{"comment"};


      push @fields_array, ($html->button($lang{CHANGE},
          "index=$index&ID=$line->{id}&TYPE_TREE=$line->{type_of_tree}&EXT_ID=$line->{ext_id}&SPECIES_ID=$line->{species_id}&AGE=$line->{age}&COORDX=$line->{coordx}&COORDY=$line->{coordy}&STATUS_EDIT=$line->{status}&COMMENT=$line->{comment}&EDIT=1"._translate($line->{position} ),
          { class => 'change' } ));
        push @fields_array, ($html->button($lang{DELETE},
          "index=$index&del=$line->{id}"._translate($line->{position} ),
          { class => 'del' } ));

        $table->addrow(@fields_array);
  }

  print $table->show();

    return 1;
}

1;
